config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tenki.urls")),
]

tenki/urls.py
from django.urls import path
from . import views

app_name    = "tenki"
urlpatterns = [
    path('', views.index, name="index"),

    #ここのtest/の部分はuuidを使うなどして予測されないように仕立てる。
    path('test/', views.admin, name="admin"),

    path("csv_download/", views.csv_download, name="csv_download")
]

tenki/models.py
from django.db import models
from django.utils import timezone


class Weather(models.Model):

    place = models.CharField(verbose_name="場所",max_length=20)
    dt    = models.DateTimeField(verbose_name="投稿日",default=timezone.now)
    today = models.CharField(verbose_name="今日の天気",max_length=150)
    tomorrow = models.CharField(verbose_name="明日の天気",max_length=150)

    today_high_temp = models.IntegerField(verbose_name="今日の最高気温(℃)")
    today_low_temp = models.IntegerField(verbose_name="今日の最低気温(℃)")
    tomorrow_high_temp = models.IntegerField(verbose_name="明日の最高気温(℃)")
    tomorrow_low_temp = models.IntegerField(verbose_name="明日の最低気温(℃)")

    """
    def __str__(self):
        return self.place
    """

tenki/forms.py
from django import forms
from django.core.validators import MinValueValidator,MaxValueValidator

#モデルを継承しないフォームクラス
class YearMonthForm(forms.Form):
    year    = forms.IntegerField()
    month   = forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(12)])

class YearForm(forms.Form):
    year    = forms.IntegerField()

class MonthForm(forms.Form):
    month   = forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(12)])

tenki/views.py
from django.shortcuts import render
from django.views import View

from .models import Weather
from .forms import YearMonthForm,YearForm,MonthForm

from django.core.paginator import Paginator 
from django.db.models.functions import TruncMonth
from django.db.models import Avg

import datetime 


PAGE_NUM    = 10

class IndexView(View):

    def get(self, request, *args, **kwargs):

        context = {}

        #ページ上部に最新の天気を数件表示させる
        #context["weather"]  = Weather.objects.order_by("-dt").first()
        context["weathers"] = Weather.objects.order_by("-dt")[:3]

        weathers = Weather.objects.filter(dt__year="2022",dt__month="13").order_by("-dt")
        print(weathers)

        if "year" in request.GET:
            print(type(request.GET["year"]))
            print(request.GET["year"])

        #ここで年月検索を行う。パラメーターの値をバリデーション、未指定もしくは間違った値が指定されている場合、全て表示させる。
        ym_form    = YearMonthForm(request.GET)

        y_form     = YearForm(request.GET)
        m_form     = MonthForm(request.GET)

        #年と月両方指定
        if ym_form.is_valid():
            cleaned         = ym_form.clean()
            all_weathers    = Weather.objects.filter(dt__year=cleaned["year"],dt__month=cleaned["month"]).order_by("-dt")
        
        #年だけ指定
        elif y_form.is_valid():
            cleaned         = y_form.clean()
            all_weathers    = Weather.objects.filter(dt__year=cleaned["year"]).order_by("-dt")

        #月だけ指定
        elif m_form.is_valid():
            cleaned         = m_form.clean()
            all_weathers    = Weather.objects.filter(dt__month=cleaned["month"]).order_by("-dt")

        #いずれも指定なし
        else:
            all_weathers    = Weather.objects.order_by("-dt")


        #1ページ表示させるページ数を指定
        paginator   = Paginator(all_weathers,PAGE_NUM)

        #何ページ目を表示させるかの指定
        if "page" in request.GET:
            all_weathers    = paginator.get_page(request.GET["page"])
        else:
            all_weathers    = paginator.get_page(1)
        
        #TODO:ここでページネーションを実装する。ただし、検索機能とページ移動を両立させなければならない。
        #https://noauto-nolife.com/post/django-paginator/
        context["all_weathers"] = all_weathers


        #年月入力のための最古と最新データを抜き取り、年月のリストを作る。
        #FIXED:データ無い場合も考慮
        oldest   = Weather.objects.order_by("dt").first()
        newest   = Weather.objects.order_by("-dt").first()

        if oldest and newest:
            oldest_dt   = oldest.dt
            newest_dt   = newest.dt
        else:
            oldest_dt   = datetime.date.today()
            newest_dt   = datetime.date.today()


        oldest_year = oldest_dt.year
        newest_year = newest_dt.year
        print(oldest_year)
        print(newest_year)
        
        """
        years   = []
        for i in range(newest_year,oldest_year-1,-1):
            years.append(i)

        context["years"]    = years
        """

        #リストの内包表記
        #https://note.nkmk.me/python-list-comprehension/
        context["months"]   = [ i for i in range(1,13) ]
        context["years"]    = [ i for i in range(newest_year,oldest_year-1,-1) ]


        #月ごとの平均気温の出力(TruncMonthで月ごとに集計し、最高気温と最低気温の平均を生成、最後に月でソーティングする。)
        #https://noauto-nolife.com/post/django-models-trunc/
        monthly_temp  = Weather.objects.annotate(monthly=TruncMonth("dt")).values("monthly").annotate(
                    today_high_temp_avg = Avg("today_high_temp"),today_low_temp_avg = Avg("today_low_temp")
                    ).values("monthly","today_high_temp_avg","today_low_temp_avg").order_by("-monthly")

        print(monthly_temp)

        return render(request,"tenki/index.html",context)

index   = IndexView.as_view()


from django.http import HttpResponse,HttpResponseNotFound
#新着3000件だけ残してそれ以前は消す
LIMIT   = 3000

class AdminView(View):

    def get(self, request, *args, **kwargs):

        #ログイン済みである
        if request.user.is_authenticated:
            #ユーザーが管理者ユーザーであることをチェック
            if request.user.is_staff:
                weathers    = Weather.objects.order_by("-dt")[LIMIT:]
                
                #weathers.delete()

                #TIPS:LIMITで絞り込んだ状態で.delete()メソッドは使えない
                for weather in weathers:
                    Weather.objects.filter(id=weather.id).delete()

                #ここで削除されたデータが出てくる(モデルオブジェクトは作られているので、
                #データを削除したあとに表示することもできる。)
                print(weathers)                

                return HttpResponse()

        return HttpResponseNotFound()

admin   = AdminView.as_view()


import csv

#https://docs.djangoproject.com/en/4.0/howto/outputting-csv/#using-the-python-csv-library
class CsvDownloadView(View):

    def get(self, request, *args, **kwargs):

        response = HttpResponse(
                content_type='text/csv',
                headers={'Content-Disposition': 'attachment; filename="somefilename.csv"'},
                )
        writer = csv.writer(response)

        #TODO:ここで検索処理を実行して、当てはまるモデルオブジェクトを順次並べてCSVを作る。
        weathers    = Weather.objects.order_by("-dt")

        for weather in weathers:

            #TODO:どうやってもここでTIMEZONEが無視される。
            d = str(weather.dt.year) + "/" + str(weather.dt.month ).zfill(2) + "/" + str(weather.dt.day).zfill(2)
            t = str(weather.dt.hour).zfill(2) + ":" + str(weather.dt.minute).zfill(2) + ":" + str(weather.dt.second).zfill(2)

            print(d)
            print(t)

            writer.writerow([ weather.place, weather.dt.strftime("%Y-%m-%d"),
                weather.dt.strftime("%H:%M:%S"), weather.today, weather.tomorrow,
                weather.today_high_temp, weather.today_low_temp,
                weather.tomorrow_high_temp, weather.tomorrow_low_temp
                ])

        return response

csv_download    = CsvDownloadView.as_view()

templates/tenki/index.html
{% load param_change %}
{# ↑テンプレートタグを読み込んで使う。 #}


<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>今日と明日の天気</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>



</head>
<body>

    <h1 class="bg-primary text-white text-center">今日と明日の天気</h1>

    <main class="container">


        <h2>新着の天気データ</h2>

        <table class="table table-striped text-center">
            <thead class="thead-dark">
                <tr>
                    <th>場所</th>
                    <th>時刻</th>
                    <th>今日の天気</th>
                    <th>今日の最高気温</th>
                    <th>今日の最低気温</th>
                    <th>明日の天気</th>
                    <th>明日の最高気温</th>
                    <th>明日の最低気温</th>
                </tr>
            </thead>
            <tbody>
                {% for weather in weathers %}
                <tr>
                    <td>{{ weather.place                }}</td>
                    <td>{{ weather.dt                   }}</td>
                    <td>{{ weather.today                }}</td>
                    <td>{{ weather.today_high_temp      }}℃</td>
                    <td>{{ weather.today_low_temp       }}℃</td>
                    <td>{{ weather.tomorrow             }}</td>
                    <td>{{ weather.tomorrow_low_temp    }}℃</td>
                    <td>{{ weather.tomorrow_high_temp   }}℃</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


        <h2>過去の天気データ</h2>

        <a href="{% url 'tenki:csv_download' %}?{% url_replace request 'page' 1 %}">検索結果でダウンロード</a>

        <input id="csv_download" type="button" value="このページをCSVにする">


        <form action="" method="GET">
            <select name="year">
                <option value="">--年</option>
                {% for year in years %}
                <option value="{{ year }}">{{ year }}年</option>
                {% endfor %}
            </select>
            <select name="month">
                <option value="">--月</option>
                {% for month in months %}
                <option value="{{ month }}">{{ month }}月</option>
                {% endfor %}
            </select>
            <input type="submit" value="検索">
        </form>

        <table class="table table-striped text-center">
            <thead class="thead-dark">
                <tr>
                    <th>場所</th>
                    <th>時刻</th>
                    <th>今日の天気</th>
                    <th>今日の最高気温</th>
                    <th>今日の最低気温</th>
                    <th>明日の天気</th>
                    <th>明日の最高気温</th>
                    <th>明日の最低気温</th>
                </tr>
            </thead>
            <tbody id="weather_data">
                {% for weather in all_weathers %}
                <tr>
                    <td>{{ weather.place                }}</td>
                    <td>{{ weather.dt                   }}</td>
                    <td>{{ weather.today                }}</td>
                    <td>{{ weather.today_high_temp      }}℃</td>
                    <td>{{ weather.today_low_temp       }}℃</td>
                    <td>{{ weather.tomorrow             }}</td>
                    <td>{{ weather.tomorrow_low_temp    }}℃</td>
                    <td>{{ weather.tomorrow_high_temp   }}℃</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <ul class="pagination">
            {% if all_weathers.has_previous %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' all_weathers.previous_page_number %}">Prev</a></li>
            {% endif %}
            <li class="page-item"><span class="page-link">{{ all_weathers.number }}</span></li>
            {% if all_weathers.has_next %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' all_weathers.next_page_number %}">Next</a></li>
            {% endif %}
        </ul>


    </main>


<script>

    $("#csv_download").on("click",function(){ create_csv(); });

function create_csv(){

    //TODO:ここで日時を整形したほうがよい
    console.log( $("#weather_data > tr > td:nth-child(1)") );

    places              = $("#weather_data > tr > td:nth-child(1)")
    dts                 = $("#weather_data > tr > td:nth-child(2)")
    todays              = $("#weather_data > tr > td:nth-child(3)")
    tomorrows           = $("#weather_data > tr > td:nth-child(4)")
    today_high_temps    = $("#weather_data > tr > td:nth-child(5)")
    today_low_temps     = $("#weather_data > tr > td:nth-child(6)")
    tomorrow_high_temps = $("#weather_data > tr > td:nth-child(7)")
    tomorrow_low_temps  = $("#weather_data > tr > td:nth-child(8)")

    console.log(places.eq(2).text())

    length  = places.length;

    data    = []
    for (let i=0;i<length;i++){
        let row = [];

        row.push(places.eq(i).text()             );
        row.push(dts.eq(i).text()                );
        row.push(todays.eq(i).text()             );
        row.push(tomorrows.eq(i).text()          );
        row.push(today_high_temps.eq(i).text()   );
        row.push(today_low_temps.eq(i).text()    );
        row.push(tomorrow_high_temps.eq(i).text());
        row.push(tomorrow_low_temps.eq(i).text() );

        data.push(row);
    }

    console.log(data);

    //作った二次元配列をCSV文字列に直す。
    let csv_string  = "";
    for (let d of data) {
        csv_string += d.join(",");
        csv_string += '\r\n';
    }

    let file_name   = "test.csv";

    //CSVのバイナリデータを作る
    let blob        = new Blob([csv_string], {type: "text/csv"});
    let uri         = URL.createObjectURL(blob);

    //リンクタグを作る
    let link        = document.createElement("a");
    link.download   = file_name;
    link.href       = uri;

    //作ったリンクタグをクリックさせる
    document.body.appendChild(link);
    link.click();

    //クリックしたら即リンクタグを消す
    document.body.removeChild(link);
    delete link;
}
</script>

</body>
</html>